# Generated by Django 3.0 on 2021-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0004_auto_20210104_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
